name: sensortag-app 
version: '0.1' 
#list of architectures the snap may run on. Defaults to [all].
#architectures: 
#	- all | amd64 | i386 | armhf
architectures: [ armhf ]
summary: Fetching TI-Sensortag data and writing it into a file 
description: |
     This snap app fetch the sensor's data from TI-Sensortag CC2650 and 
     Write the Data into a file
grade:  devel
confinement: devmode

apps:
  run:
    command: bin/nodeapp
    plugs: [bluetooth-control, network-bind, network]
  hciconfig:
    command: usr/bin/hciconfig
    plugs: [  bluetooth-control ]
  hcitool:
    command: usr/bin/hcitool
    plugs: [ bluetooth-control ]
  bluetoothctl:
    command: usr/bin/bluetoothctl
    plugs: [ client ]
  bluez:
    command: "usr/lib/bluetooth/bluetoothd -E"
    daemon: simple
    slots: [ service ]

plugs:
  client:
      interface: bluez

slots:
  service:
      interface: bluez

parts:
  starfish-sdk-wrapper:
    source: .
    plugin: nodejs
    node-packages: 
      - request-promise-native
      - inotify
      - jsonwebtoken
      -  request@^2.34

  bluepy:
    plugin: python
    source: bluepy
    build-packages: [libglib2.0-dev]

  bluez:
    plugin: autotools
    source: https://www.kernel.org/pub/linux/bluetooth/bluez-5.43.tar.xz
    #source: bluez-5.43 
    configflags:
      - --prefix=/usr
      - --libexec=/usr/lib/
      - --enable-experimental
      - --enable-snappy
      - --enable-threads
      - --disable-cups
      - --disable-monitor
      - --enable-obex
      - --disable-systemd
      - --disable-silent-rules
    build-packages:
      - libglib2.0-dev
      - libdbus-1-dev
      - libical-dev
      - libreadline6-dev
      - libudev-dev
      - pkg-config
      - quilt
    stage-packages:
      - libical1a
    filesets:
      libical1a:
        - usr/lib/*/libical*
    prime:
      - usr/lib/bluetooth/bluetoothd
      - usr/bin/bluetoothctl
      - usr/bin/hciconfig
      - usr/bin/hcitool
      - usr/share/doc/libical1a/copyright
      - $libical1a

  move:
     plugin: dump
     source: bin
     organize:
       sensortagUpdate: bin/sensortagUpdate  

